

CREATE TABLE MEETBOARD (
	BOARD_NO VARCHAR2(20) NOT NULL,
	BOARD_TITLE VARCHAR2(40) NOT NULL,
	BOARD_CONTENT VARCHAR2(2000) NOT NULL,
	BOARD_DATE DATE NOT NULL,
	USER_NO VARCHAR2(20) NOT NULL,
	MEET_NO VARCHAR2(20) NOT NULL,
	
	CONSTRAINT MEETBOARD_PK PRIMARY KEY (
		BOARD_NO
	)
	ENABLE,
	
	CONSTRAINT MEETBOARD_FK_MEET FOREIGN KEY (MEET_NO)
	REFERENCES MEET(MEET_NO)
);


DROP TABLE meetboard;

SELECT * FROM MEETBOARD order by BOARD_NO desc;

-----------------------
-- INSERT DUMMY DATA IN MEET BOARD --
-----------------------

INSERT INTO MEETBOARD(BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, USER_NO, MEET_NO) VALUES ('B'||SEQ_MEETBOARD.nextval, '테스트', '테스트?', TO_DATE(SYSDATE, 'YYYYMMDD'), 'U1001', 'M1002');
INSERT INTO MEETBOARD(BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, USER_NO, MEET_NO) VALUES ('B'||SEQ_MEETBOARD.nextval, '테스트', '테스트?', TO_DATE(SYSDATE, 'YYYYMMDD'), 'U1002', 'M1001');
INSERT INTO MEETBOARD(BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, USER_NO, MEET_NO) VALUES ('B'||SEQ_MEETBOARD.nextval, '테스트', '테스트?', TO_DATE(SYSDATE, 'YYYYMMDD'), 'U1003', 'M1001');

---------------------
-- SysDateTime 설정 --
---------------------
select TO_DATE(SYSDATE, 'YYYY-MM-DD') as now from dual;
select sysdate, current_date, dbtimezone, sessiontimezone from dual;
alter session set nls_date_format='YYYYMMDD';


DROP VIEW BOARD_INIT_VIEW;

------------
-- SELECT --
------------
SELECT
    M.MEET_NO,
    M.MEET_NAME,
    M.USER_NO, 
    MB.BOARD_NO, 
    MB.BOARD_TITLE, 
    MB.BOARD_CONTENT, 
    MB.USER_NO AS MD_USER_NO, 
    MB.MEET_NO AS MD_MEET_NO
FROM 
    MEET M 
JOIN 
    MEETBOARD MB
ON 
    M.MEET_NO = MB.MEET_NO
ORDER BY 
    MB.BOARD_NO DESC;

SELECT * FROM MEETBOARD order by BOARD_NO desc;

----------------------------------
-- SELECT JOIN : USER MEETBOARD --
----------------------------------

SELECT 
    U.USER_NO as USER_NO, U.USER_NAME AS USER_NAME, MB.BOARD_NO AS BOARD_NO, MB.BOARD_TITLE AS BOARD_TITLE, MB.BOARD_CONTENT AS BOARD_CONTENT, MB.BOARD_DATE AS BOARD_DATE, MB.MEET_NO AS MEET_NO
FROM TEST_USER U LEFT JOIN MEETBOARD MB
ON U.USER_NO = MB.USER_NO;


----------------------------------
-- CREATE VIEW : USER MEETBOARD --
----------------------------------

CREATE VIEW MEETBOARD_USER_VIEW (
    USER_NO,
    USER_NAME,
    BOARD_NO,
    BOARD_TITLE,
    BOARD_CONTENT,
    BOARD_DATE,
    MEET_NO
) AS
SELECT U.USER_NO as USER_NO, U.USER_NAME AS USER_NAME, MB.BOARD_NO AS BOARD_NO, MB.BOARD_TITLE AS BOARD_TITLE, MB.BOARD_CONTENT AS BOARD_CONTENT, MB.BOARD_DATE AS BOARD_DATE, MB.MEET_NO AS MEET_NO
FROM TEST_USER U JOIN MEETBOARD MB
ON U.USER_NO = MB.USER_NO;

SELECT U.USER_NO as USER_NO, U.USER_NAME AS USER_NAME, MB.BOARD_NO AS BOARD_NO, MB.BOARD_TITLE AS BOARD_TITLE, MB.BOARD_CONTENT AS BOARD_CONTENT, MB.BOARD_DATE AS BOARD_DATE, MB.MEET_NO AS MEET_NO
FROM TEST_USER U JOIN MEETBOARD MB
ON U.USER_NO = MB.USER_NO;

----------------------------------
-- DROP VIEW : USER MEETBOARD --
----------------------------------
DROP VIEW MEETBOARD_USER_VIEW;

-------------------------------------
-- SELECT ALL FOR MEET MAIN (FEED) --
-------------------------------------

SELECT 
    USER_NO, 
    USER_NAME, BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, MEET_NO FROM MEETBOARD_USER_VIEW ORDER BY BOARD_NO DESC;
SELECT * FROM MEETBOARD_USER_VIEW;

-- SELECT ONE FOR MEET POST DETAIL
SELECT * FROM MEETBOARD_USER_VIEW WHERE BOARD_NO='B1004';
SELECT * FROM MEETBOARD_USER_VIEW WHERE BOARD_NO=?;


------------------
-- DELETE BOARD --
------------------

DELETE FROM MEETBOARD WHERE BOARD_NO='B1002';

------------------
-- UPDATE BOARD --
------------------
UPDATE MEETBOARD SET BOARD_TITLE=?,  BOARD_CONTENT=?, BOARD_DATE=SYSDATE WHERE BOARD_NO=?;
UPDATE MEETBOARD SET BOARD_TITLE='update test',  BOARD_CONTENT='update test', BOARD_DATE=SYSDATE WHERE BOARD_NO='B1024';