CREATE OR REPLACE VIEW ACTI_LIKE_VIEW (
    ACTIVITY_NO,
    LIKE_CNT
) AS (
    SELECT ACTIVITY_NO, COUNT(ACTIVITY_NO)
    FROM TEST_ACTIVITY_LIKE GROUP BY ACTIVITY_NO
);


CREATE OR REPLACE VIEW ACTI_LIKE_JOIN_VIEW (
    ACTIVITY_NO, ACTIVITY_IMAGE, ACTIVITY_NAME, ACTIVITY_DESCRIPTION, ACTIVITY_CITY, ACTIVITY_COUNTY, ACTIVITY_INTEREST_NAME, ACTIVITY_GENDER, ACTIVITY_NOP, ACTIVITY_AGE, ACTIVITY_DATE, USER_NO, MEET_NO, LIKE_CNT
) AS (
    SELECT A.ACTIVITY_NO, A.ACTIVITY_IMAGE, A.ACTIVITY_NAME, A.ACTIVITY_DESCRIPTION, A.ACTIVITY_CITY, A.ACTIVITY_COUNTY, A.ACTIVITY_INTEREST_NAME, A.ACTIVITY_GENDER, A.ACTIVITY_NOP, A.ACTIVITY_AGE, A.ACTIVITY_DATE, A.USER_NO, A.MEET_NO, NVL(LIKE_CNT, 0)
    FROM TEST_ACTIVITY A
    LEFT OUTER JOIN ACTI_LIKE_VIEW AV
    ON A.ACTIVITY_NO = AV.ACTIVITY_NO
);



CREATE OR REPLACE VIEW ACTI_USER_CNT_VIEW(
    ACTIVITY_NO, USER_CNT
) AS (
    SELECT ACTIVITY_NO, COUNT(ACTIVITY_NO)
    FROM TEST_ACTIVITY_REGISTERED GROUP BY ACTIVITY_NO
);


-------------------------------
-- ACTIVITY :: 좋아요 순으로 정렬 --
-------------------------------
CREATE OR REPLACE VIEW ACTI_USER_LIKE_VIEW (
    ACTIVITY_NO, ACTIVITY_IMAGE, ACTIVITY_NAME, ACTIVITY_DESCRIPTION, ACTIVITY_COUNTY, ACTIVITY_INTEREST_NAME, ACTIVITY_GENDER, ACTIVITY_NOP, ACTIVITY_AGE, ACTIVITY_DATE, USER_NO, MEET_NO, LIKE_CNT, USER_CNT
) AS (
    SELECT A.ACTIVITY_NO, ACTIVITY_IMAGE, ACTIVITY_NAME, ACTIVITY_DESCRIPTION, ACTIVITY_COUNTY, ACTIVITY_INTEREST_NAME, ACTIVITY_GENDER, ACTIVITY_NOP, ACTIVITY_AGE, ACTIVITY_DATE, USER_NO, MEET_NO, LIKE_CNT, NVL(USER_CNT, 0)
    FROM ACTI_LIKE_JOIN_VIEW A
    LEFT OUTER JOIN ACTI_USER_CNT_VIEW U
    ON A.ACTIVITY_NO = U.ACTIVITY_NO
);


--------------------------------
-- ACTIVITY LIST :: VOTE LIST --
--------------------------------
CREATE OR REPLACE VIEW  VOTE_USER_VIEW AS 
SELECT V.VOTE_NO, VOTE_TITLE, VOTE_DESCRIPTION, VOTE_EOD, VOTE_STATE, V.USER_NO, ACTIVITY_NO, USER_CNT
FROM TEST_VOTE V LEFT OUTER JOIN (SELECT VOTE_NO, COUNT(USER_NO) AS USER_CNT FROM TEST_VOTE_RESULT GROUP BY VOTE_NO) VR
ON V.VOTE_NO=VR.VOTE_NO;