-- 로그인을 안 했을 때 모임의 좋아요 순으로 정렬

SELECT * FROM TEST_MEET;

CREATE OR REPLACE VIEW LIKE_VIEW (
    MEET_NO,
    LIKE_CNT
) AS (
    SELECT MEET_NO, COUNT(MEET_NO)
    FROM TEST_MEET_LIKE GROUP BY MEET_NO
);

SELECT * FROM LIKE_VIEW;

CREATE OR REPLACE VIEW MEET_LIKE_VIEW (
    MEET_NO, MEET_IMAGE, MEET_NAME, MEET_DESCRIPTION, MEET_CITY, MEET_COUNTY, MEET_INTEREST_NAME, MEET_GENDER, MEET_NOP, MEET_AGE, MEET_DATE, USER_NO, LIKE_CNT
) AS (
    SELECT M.MEET_NO, MEET_IMAGE, MEET_NAME, MEET_DESCRIPTION, MEET_CITY, MEET_COUNTY, MEET_INTEREST_NAME, MEET_GENDER, MEET_NOP, MEET_AGE, MEET_DATE, USER_NO, NVL(LIKE_CNT, 0)
    FROM TEST_MEET M
    LEFT OUTER JOIN LIKE_VIEW LV
    ON M.MEET_NO = LV.MEET_NO
);

create or replace view USER_CNT_VIEW (
    meet_no, user_cnt
) as (
    select meet_no, count(meet_no)
    from test_meet_registered group by meet_no
);

select * from user_cnt_view;


--------------------------
-- 좋아요 순으로 정렬 :: 최종 --
--------------------------
CREATE OR REPLACE VIEW MEET_USER_LIKE_VIEW (
    MEET_NO, MEET_IMAGE, MEET_NAME, MEET_DESCRIPTION, MEET_CITY, MEET_COUNTY, MEET_INTEREST_NAME, MEET_GENDER, MEET_NOP, MEET_AGE, MEET_DATE, USER_NO, LIKE_CNT, USER_CNT
) AS (
    SELECT m.MEET_NO, MEET_IMAGE, MEET_NAME, MEET_DESCRIPTION, MEET_CITY, MEET_COUNTY, MEET_INTEREST_NAME, MEET_GENDER, MEET_NOP, MEET_AGE, MEET_DATE, USER_NO, LIKE_CNT, NVL(USER_CNT, 0)
    FROM MEET_LIKE_VIEW m
    LEFT OUTER JOIN USER_CNT_VIEW c
    ON m.MEET_NO = c.MEET_NO
);

SELECT * FROM MEET_USER_LIKE_VIEW WHERE MEET_NAME LIKE '%%';
SELECT * FROM MEET_USER_LIKE_VIEW WHERE MEET_INTEREST_NAME = '친목/모임' AND MEET_NAME LIKE '%%';


