CREATE TABLE TEST_USER
(
  USER_NO VARCHAR2(20) NOT NULL 
, USER_IMAGE VARCHAR2(20) 
, USER_ID VARCHAR2(40) NOT NULL 
, USER_PW VARCHAR2(60) NOT NULL 
, USER_NAME VARCHAR2(40) NOT NULL 
, USER_NICKNAME VARCHAR2(40) NOT NULL 
, USER_EMAIL VARCHAR2(160) NOT NULL 
, USER_TEL VARCHAR2(52) NOT NULL 
, USER_BIRTH DATE NOT NULL 
, USER_GENDER VARCHAR2(8) NOT NULL 
, USER_CITY VARCHAR2(40) 
, USER_COUNTY VARCHAR2(40) 
, USER_STATE CHAR NOT NULL
, USER_INTEREST VARCHAR2(60) 
, CONSTRAINT TEST_USER_PK PRIMARY KEY
  (
    USER_NO 
  )
  ENABLE 
);
CREATE SEQUENCE SEQ_TEST_USER INCREMENT BY 1 START WITH 1001;

COMMENT ON COLUMN TEST_USER.USER_STATE IS '계정 life 유무';

insert into TEST_USER(USER_NO, USER_ID, USER_PW, USER_NAME, USER_NICKNAME, USER_EMAIL, USER_TEL, USER_BIRTH, USER_GENDER, USER_CITY, USER_COUNTY, USER_STATE, USER_INTEREST)
values ('U'||SEQ_TEST_USER.nextval, 'qjspdl', 'dks55634', '김예은', '예으니', 'qjspdl@hs.ac.kr', '010-4068-5633', '19980131', 'F', '경기도', '광주시', 'Y', '취미');
insert into TEST_USER(USER_NO, USER_ID, USER_PW, USER_NAME, USER_NICKNAME, USER_EMAIL, USER_TEL, USER_BIRTH, USER_GENDER, USER_CITY, USER_COUNTY, USER_STATE, USER_INTEREST)
values ('U'||SEQ_TEST_USER.nextval, 'choi_true', 'true44', '최진실', '최트루', 'choitrue@naver.com', '010-1234-5678', '19970404', 'F', '경기도', '광주시', 'Y', '팬클럽');
insert into TEST_USER(USER_NO, USER_ID, USER_PW, USER_NAME, USER_NICKNAME, USER_EMAIL, USER_TEL, USER_BIRTH, USER_GENDER, USER_CITY, USER_COUNTY, USER_STATE, USER_INTEREST)
values ('U'||SEQ_TEST_USER.nextval, 'pani', 'geuni123', '전판근', '파니그니', 'pani@naver.com', '010-2343-2350', '19970809', 'M', '서울특별시', '역삼동', 'Y', null);
commit;
