-- (TEST_VOTE) DROP TABLE
DROP TABLE TEST_VOTE;

-- (TEST_VOTE) CREATE TABLE
CREATE TABLE TEST_VOTE 
(
  VOTE_NO VARCHAR2(50 BYTE) NOT NULL 
, VOTE_TITLE VARCHAR2(60 BYTE) NOT NULL 
, VOTE_CONTENT VARCHAR2(600 BYTE) NOT NULL 
, VOTE_EOD DATE NOT NULL 
, VOTE_STATE CHAR NOT NULL 
, USER_NO VARCHAR2(50 BYTE) NOT NULL 
, MEET_NO VARCHAR2(50 BYTE) 
, ACTIVITY_NO VARCHAR2(50 BYTE) 
, CONSTRAINT TEST_VOTE_PK PRIMARY KEY 
  (
    VOTE_NO 
  )
  ENABLE 
);


-- (TEST_VOTE) PRIMARY KEY SET
ALTER TABLE TEST_VOTE
ADD CONSTRAINT TEST_VOTE_FK1 FOREIGN KEY
(
  USER_NO 
)
REFERENCES TEST_USER
(
  USER_NO 
)
ENABLE;


-- (TEST_VOTE) FOREIGN KEY SET
ALTER TABLE TEST_VOTE
ADD CONSTRAINT TEST_VOTE_FK2 FOREIGN KEY
(
  MEET_NO 
)
REFERENCES TEST_MEET
(
  MEET_NO 
)
ENABLE;

ALTER TABLE TEST_VOTE
ADD CONSTRAINT TEST_VOTE_FK3 FOREIGN KEY
(
  ACTIVITY_NO 
)
REFERENCES TEST_ACTIVITY
(
  ACTIVITY_NO 
)
ENABLE;


-- SEQUENCE CREATE
DROP SEQUENCE SEQ_TEST_VOTE;
CREATE SEQUENCE SEQ_TEST_VOTE INCREMENT BY 1 START WITH 1001;


TRUNCATE TABLE TEST_VOTE;

INSERT INTO TEST_VOTE(VOTE_NO, VOTE_TITLE, VOTE_CONTENT, VOTE_EOD, VOTE_STATE, USER_NO, MEET_NO, ACTIVITY_NO)
VALUES ('V'||SEQ_TEST_VOTE.NEXTVAL, '가장 좋아하는 원두는?', '본인이 가장 좋아하는 원두에 투표해주세요!', TO_DATE('2022/09/30 23:59:59','YYYY/MM/DD hh24:mi:ss'), 'N', 'U1002', 'M1001', null);
commit;
ROLLBACK;

--------------------------------------------------------------------------------------------------------------------


-- (TEST_VOTE_CONTENT) CREATE TABLE
CREATE TABLE TEST_VOTE_CONTENT 
(
  CONTENT_NO VARCHAR2(50 BYTE) NOT NULL 
, VOTE_NO VARCHAR2(50 BYTE) NOT NULL 
, VOTE_CONTENT VARCHAR2(200 BYTE) NOT NULL 
, CONSTRAINT TEST_VOTE_CONTENT_PK PRIMARY KEY 
  (
    CONTENT_NO 
  )
  ENABLE 
);

ALTER TABLE TEST_VOTE_CONTENT
ADD CONSTRAINT TEST_VOTE_CONTENT_FK1 FOREIGN KEY
(
  VOTE_NO 
)
REFERENCES TEST_VOTE
(
  VOTE_NO 
)
ENABLE;


-- SEQUENCE CREATE
DROP SEQUENCE SEQ_TEST_VOTE_CONTENT;
CREATE SEQUENCE SEQ_TEST_VOTE_CONTENT INCREMENT BY 1 START WITH 1001;

INSERT INTO TEST_VOTE_CONTENT(CONTENT_NO, VOTE_NO, VOTE_CONTENT)
VALUES ('VC'||SEQ_TEST_VOTE_CONTENT.NEXTVAL, 'V1001', '아라비아 원두');
commit;
ROLLBACK;