SELECT * FROM MEETBOARD;


CREATE TABLE TEST_COMMENT (
    COMMENT_NO VARCHAR2(100 BYTE) NOT NULL,
    MOTHER_NO VARCHAR2(100 BYTE),
    COMMENT_DATE DATE NOT NULL,
    COMMENT_CONTENT VARCHAR2(1000 BYTE) NOT NULL,
    BOARD_NO VARCHAR2(100 BYTE) NOT NULL,
    USER_NO VARCHAR2(100 BYTE) NOT NULL,
    
    CONSTRAINT TEST_COMMENT_PK PRIMARY KEY (
        COMMENT_NO
    )
    ENABLE,
    
    CONSTRAINT TEST_COMMENT_FK1 FOREIGN KEY (BOARD_NO)
    REFERENCES MEETBOARD(BOARD_NO),
    
    CONSTRAINT TEST_COMMENT_FK2 FOREIGN KEY (USER_NO)
    REFERENCES TEST_USER(USER_NO)
);
DROP TABLE TEST_COMMENT;

CREATE SEQUENCE SEQ_COMMENT INCREMENT BY 1 START WITH 1001;
DROP SEQUENCE SEQ_COMMENT;

SELECT * FROM TEST_COMMENT;


CREATE OR REPLACE VIEW COMMENT_VIEW (
    COMMENT_NO, MOTHER_NO, COMMENT_DATE, COMMENT_CONTENT, BOARD_NO, USER_NO, USER_IMAGE, USER_NICKNAME
) AS (
    SELECT 
        c.COMMENT_NO, 
        c.MOTHER_NO, 
        c.COMMENT_DATE, 
        c.COMMENT_CONTENT, 
        c.BOARD_NO, 
        c.USER_NO, 
        u.USER_IMAGE, 
        u.USER_NICKNAME
    FROM TEST_COMMENT c
    LEFT OUTER JOIN TEST_USER u
    ON c.USER_NO = u.USER_NO
);

SELECT * FROM COMMENT_VIEW WHERE BOARD_NO = 'B1057' ORDER BY COMMENT_NO DESC;