-- (TEST_EVENT) CREATE TABLE
CREATE TABLE TEST_EVENT(	
    EVENT_NO VARCHAR2(50 BYTE) NOT NULL, 
	EVENT_TITLE VARCHAR2(40 BYTE) NOT NULL, 
	EVENT_DESCRIPTION VARCHAR2(1000 BYTE) NOT NULL,
	EVENT_DATE DATE NOT NULL, 
    EVENT_D_DAY DATE NOT NULL,
    ACTIVITY_NO VARCHAR2(50 BYTE) NOT NULL,
	USER_NO VARCHAR2(50 BYTE) NOT NULL
);

-- (TEST_EVENT) PRIMARY KEY SET
ALTER TABLE TEST_EVENT
ADD CONSTRAINT TEST_EVENT_PK PRIMARY KEY
(
  EVENT_NO 
)
ENABLE;

-- (TEST_EVENT) FOREIGN KEY SET
ALTER TABLE TEST_EVENT
ADD CONSTRAINT TEST_EVENT_FK1 FOREIGN KEY
(
  ACTIVITY_NO 
)
REFERENCES TEST_ACTIVITY
(
  ACTIVITY_NO 
)
ENABLE;

ALTER TABLE TEST_EVENT
ADD CONSTRAINT TEST_EVENT_FK2 FOREIGN KEY
(
  USER_NO 
)
REFERENCES TEST_USER
(
  USER_NO 
)
ENABLE;

-- SEQUENCE CREATE
CREATE SEQUENCE SEQ_TEST_EVENT INCREMENT BY 1 START WITH 1001;

insert into TEST_EVENT(EVENT_NO, EVENT_TITLE, EVENT_DESCRIPTION, EVENT_DATE, EVENT_D_DAY, ACTIVITY_NO, USER_NO) 
values ('E'||SEQ_TEST_EVENT.NEXTVAL, '제2회 정기모임 행사', '제2회 정기모임 행사를 진행하려합니다!\n오랜만에 진행하는 행사이니만큼 많은 참석부탁드려요~', sysdate, '2022-10-10 12:00:00', 'A1001', 'U1001');
commit;

select sysdate from dual;